import { IProvider } from './provider.interface';

const OutlookProvider: IProvider = {
  getNormalizedAddress(emailAddress: string): string {
    const emailAddressToReturn = emailAddress.toLocaleLowerCase().split('@');
    const domain = emailAddressToReturn[1];

    // eslint-disable-next-line @typescript-eslint/no-use-before-define
    if (!validOutlookDomains.find((dm) => dm === domain)) {
      throw new Error(`"${domain}" is not a valid Microsoft Outlook domain!`);
    }

    return emailAddressToReturn[0]
      .toLowerCase()
      .replace(/(\+[^@]+)/, '')
      .concat(`@${domain}`);
  },
};

const validOutlookDomains = [
  'hotmail.com',
  'outlook.com',
  'outlook.sa',
  'windowslive.com',
  'hotmail.com.ar',
  'outlook.com.ar',
  'live.com.ar',
  'hotmail.com.au',
  'outlook.com.au',
  'live.com.au',
  'outlook.at',
  'live.at',
  'hotmail.be',
  'outlook.be',
  'live.be',
  'hotmail.com.br',
  'outlook.com.br',
  'live.com',
  'hotmail.ca',
  'live.ca',
  'hotmail.cz',
  'outlook.cz',
  'hotmail.cl',
  'outlook.cl',
  'live.cl',
  'live.cn',
  'hotmail.dk',
  'outlook.dk',
  'live.dk',
  'hotmail.fi',
  'live.fi',
  'hotmail.fr',
  'outlook.fr',
  'live.fr',
  'hotmail.gr',
  'outlook.com.gr',
  'hotmail.de',
  'outlook.de',
  'live.de',
  'hotmail.com.hk',
  'live.hk',
  'hotmail.hu',
  'outlook.hu',
  'hotmail.co.in',
  'outlook.in',
  'live.in',
  'hotmail.co.id',
  'outlook.co.id',
  'outlook.ie',
  'live.ie',
  'hotmail.co.il',
  'outlook.co.il',
  'hotmail.it',
  'outlook.it',
  'live.it',
  'hotmail.co.jp',
  'outlook.jp',
  'live.jp',
  'hotmail.co.kr',
  'outlook.kr',
  'live.co.kr',
  'hotmail.lv',
  'outlook.lv',
  'hotmail.lt',
  'hotmail.my',
  'outlook.my',
  'live.com.my',
  'live.com.mx',
  'hotmail.nl',
  'live.nl',
  'hotmail.no',
  'live.no',
  'hotmail.ph',
  'outlook.ph',
  'live.com.ph',
  'outlook.pt',
  'live.com.pt',
  'live.ru',
  'hotmail.rs',
  'hotmail.sg',
  'outlook.sg',
  'live.com.sg',
  'hotmail.sk',
  'outlook.sk',
  'hotmail.co.za',
  'live.co.za',
  'hotmail.es',
  'outlook.es',
  'hotmail.se',
  'live.se',
  'hotmail.com.tw',
  'livemail.tw',
  'hotmail.co.th',
  'outlook.co.th',
  'hotmail.com.tr',
  'outlook.com.tr',
  'hotmail.com.vn',
  'outlook.com.vn',
  'hotmail.co.uk',
  'live.co.uk',
];

export default OutlookProvider;
