name: Pull-requests workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - main
      - develop

jobs:
  buildAndTest:
    env:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # [12.x, 14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run test:integration
        continue-on-error: true # TODO
      - run: npm run lint
      - run: npm run mutate
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 