name: Pull-requests workflow

on:
  workflow_dispatch:
    inputs:
      deploy_docs:
        description: 'Deploy docs to GitHub Pages'
        type: boolean
        default: false
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - main
      - develop

permissions:
  id-token: write
  pages: write

jobs:
  buildAndTest:
    env:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run test:integration
        continue-on-error: true # TODO
      - run: npm run lint
      - run: npm run mutate

      - uses: codecov/codecov-action@v7
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Publish docs
        run: npm run doc-gen

      - id: upload-documentation
        name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/
          name: typedocs

  deploy-pages:
    name: Deploy documentation to GitHub Pages
    needs: buildAndTest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/develop') || (github.event_name == 'workflow_dispatch' && inputs.deploy_docs)
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
        with:
          artifact_name: typedocs